events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;

        location /modpack {
            alias /usr/share/nginx/html;
            autoindex on;
            location ~* \.tar\.gz$ {
                add_header Content-Disposition 'attachment; filename="minecraft-vpn-modpack.tar.gz"';
            }
        }

        location /mods {
            alias /usr/share/nginx/html/mods;
            autoindex on;
        }

        client_max_body_size 500M;
    }
}